In [1]:
pip install numpy

   ---------------------------------------- 0.0/12.8 MB ? eta -:--:--
   ---- ----------------------------------- 1.3/12.8 MB 5.6 MB/s eta 0:00:03
   --------- ------------------------------ 3.1/12.8 MB 7.1 MB/s eta 0:00:02
   ---------------- ----------------------- 5.2/12.8 MB 8.2 MB/s eta 0:00:01
   ------------------ --------------------- 6.0/12.8 MB 7.1 MB/s eta 0:00:01
   -------------------------- ------------- 8.4/12.8 MB 7.9 MB/s eta 0:00:01
   -------------------------------- ------- 10.5/12.8 MB 8.2 MB/s eta 0:00:01
   ---------------------------------------  12.6/12.8 MB 8.5 MB/s eta 0:00:01
   ---------------------------------------- 12.8/12.8 MB 8.0 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.2 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np

Basic Array creation

In [3]:
arr=np.array([1, 2, 3, 4, 5])
arr

array([1, 2, 3, 4, 5])

In [4]:
a=[1,2,3.45,"hi"]
a

[1, 2, 3.45, 'hi']

In [6]:
arr2=np.array(a)
arr2

array(['1', '2', '3.45', 'hi'], dtype='<U32')

In [7]:
l=[[1,2,3],[4,5,6],[7,8,9]]

In [8]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Array Generation function

In [11]:
arr3=np.arange(1,101,2)
arr3

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [4]:
arr = np.zeros((6,5))
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [5]:
arr5 = np.ones((3,4))
arr5

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [9]:
arr4=np.linspace(1,10,10)
arr4

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

Random Generation function

In [11]:
np.random.rand(10)

array([0.84202944, 0.29706842, 0.39769073, 0.40564609, 0.39461649,
       0.09063317, 0.66648642, 0.4620264 , 0.12656467, 0.90085219])

In [12]:
np.random.randn(10)

array([-0.22298964, -1.58429262, -1.16827988, -0.80796793, -0.20567179,
       -0.39562591, -0.99485744, -0.0728152 , -0.56088884, -0.79481374])

In [14]:
np.random.randint(5,20,10)

array([15, 19, 10, 15, 10,  9, 13, 14, 15, 14], dtype=int32)

Array Attributes

In [16]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
arr.shape

(3, 3)

In [19]:
arr.size

9

In [20]:
arr.dtype

dtype('int64')

Array Method 

In [21]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
arr.min()

np.int64(1)

In [23]:
arr.max()

np.int64(9)

In [25]:
arr.sum()

np.int64(45)

In [27]:
np.sum(arr,axis=0)

array([12, 15, 18])

In [28]:
arr.mean()


np.float64(5.0)

In [29]:
arr.std()

np.float64(2.581988897471611)

In [30]:
arr.argmax()

np.int64(8)

In [31]:
arr.argmin()

np.int64(0)

Reshaping and Resizing

In [33]:
arr=np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [35]:
arr=arr.reshape(5,6)

In [36]:
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])