Array Exercises

In [1]:
import numpy as np

Valid Sudoku

In [3]:
s= np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [4]:
s.sum()

np.int64(405)

In [6]:
b=np.sum(s, axis=1)  # Row-wise sum
b == 45  # Check if each row sums to 45

array([ True,  True,  True,  True,  True,  True,  True,  True,  True])

In [9]:
b=np.sum(s, axis=1)  # Row-wise sum
for i in b:
    if i!=45:
        print("Not a Sudoku")
        break
else:
    print("Valid Sudoku for Rows")

Valid Sudoku for Rows


In [8]:
b=np.sum(s, axis=0)  # Column-wise sum
for i in b:
    if i!=45:
        print("Not a Sudoku")
        break
else:
    print("Valid Sudoku for columns")

Valid Sudoku for columns


In [13]:
a=s[0:3,0:3]
a

array([[5, 3, 4],
       [6, 7, 2],
       [1, 9, 8]])

In [15]:
c=s[0:3,3:6]
c

array([[6, 7, 8],
       [1, 9, 5],
       [3, 4, 2]])

In [16]:
d=s[0:3,6:9]
d

array([[9, 1, 2],
       [3, 4, 8],
       [5, 6, 7]])

In [19]:
for i in range(0,9,3):
    for j in range(0,9,3):
        n=(s[i:i+3,j:j+3])
        print(n.sum())

45
45
45
45
45
45
45
45
45


General Questions

In [20]:
import numpy as np

# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

In [21]:
#Get the shape of the matrix.
data.shape  # (5, 3)

(5, 3)

In [23]:
#Find the average age of students.
avg_age = np.mean(data[:,0])
avg_age  # 18.4

np.float64(18.4)

In [25]:
#Extract Math marks of all students.
math_marks = data[:,1]
math_marks  # array([85, 92, 76, 65, 90])

array([85, 92, 76, 65, 90])

In [27]:
#Find the highest Science mark.
highest_science_mark = np.max(data[:,2])
highest_science_mark  # 95

np.int64(95)

In [28]:
#Get details of the student who scored more than 90 in Math.
top_math_students = data[data[:,1] > 90]
top_math_students  # array([[19, 92, 88], [20, 90, 85]])

array([[19, 92, 88]])

In [29]:
#Increase Math marks of all students by 5.
New_math_marks = data[:,1] + 5
New_math_marks  # array([90, 97, 81, 70, 95])

array([90, 97, 81, 70, 95])

In [30]:
#Find how many students are younger than 19.
young_students_count = np.sum(data[:,0]<19)
young_students_count  # 3

np.int64(3)

In [31]:
#Calculate the average marks in each subject (column-wise mean).
average_marks = np.mean(data[:,1:], axis=0)
average_marks  # array([81.6, 83.2])

array([81.6, 83.2])

In [32]:
#Get data of students who scored at least 80 in both subjects.
top_students = data[(data[:,1] >= 80) & (data[:,2] >= 80)]
top_students  # array([[19, 92, 88], [20, 90

array([[19, 92, 88],
       [20, 90, 85]])

In [33]:
#Replace all Science marks < 75 with 0.
data[data[:,2] < 75, 2] = 0
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65,  0],
       [20, 90, 85]])