Array Operations

In [3]:
import numpy as np

Arithematic Operation

In [4]:
a1=np.array([1,2,3,4,5])
a2=np.array([6,7,8,9,10])
a1
a2

array([ 6,  7,  8,  9, 10])

In [5]:
arr=a1+a2
arr

array([ 7,  9, 11, 13, 15])

In [6]:
arr1=a2-a1
arr1

array([5, 5, 5, 5, 5])

In [7]:
arr3=a1*a2
arr3

array([ 6, 14, 24, 36, 50])

In [8]:
arr4=a1/a2
arr4

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [9]:
a1//a2

array([0, 0, 0, 0, 0])

In [10]:
a1**a2

array([      1,     128,    6561,  262144, 9765625])

Broadcasting


In [11]:
l=[10,20,30,40,50]
arr=np.array(l)
arr

array([10, 20, 30, 40, 50])

In [12]:
arr+10

array([20, 30, 40, 50, 60])

In [13]:
arr2=np.arange(1,26).reshape(5,5)
arr3= np.arange(1,26).reshape(5,5)
arr2


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [14]:
arr2*arr3

array([[  1,   4,   9,  16,  25],
       [ 36,  49,  64,  81, 100],
       [121, 144, 169, 196, 225],
       [256, 289, 324, 361, 400],
       [441, 484, 529, 576, 625]])

Deep and Shallow Copy

In [15]:
a=np.arange(1,26)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [16]:
slice_a=a[:10]
slice_a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
slice_a=slice_a*10
slice_a

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [18]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [19]:
a[4:6]*10

array([50, 60])

In [20]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [21]:
a
b=a.copy()
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [22]:
b[0]=1000
b

array([1000,    2,    3,    4,    5,    6,    7,    8,    9,   10,   11,
         12,   13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
         23,   24,   25])

In [23]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

Matrix Operation

In [24]:
m1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
m2= np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])

In [25]:
m1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
m2

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [27]:
m1@m2

array([[ 30,  24,  18],
       [ 84,  69,  54],
       [138, 114,  90]])

In [28]:
m3=np.dot(m1,m2)
m3

array([[ 30,  24,  18],
       [ 84,  69,  54],
       [138, 114,  90]])

In [29]:
m3.T

array([[ 30,  84, 138],
       [ 24,  69, 114],
       [ 18,  54,  90]])

Advance Array Mmanipulation

Stacking Array

In [30]:
m1=np.array([1,2,3,4,5])
m2=np.array([6,7,8,9,10])

In [31]:
np.vstack((m1,m2))  

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [32]:
np.hstack((m1,m2))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [33]:
np.column_stack((m1,m2))

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

Splliting Array

In [36]:
a=np.arange(1,37).reshape(6,6)
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [38]:
np.hsplit(a,6)

[array([[ 1],
        [ 7],
        [13],
        [19],
        [25],
        [31]]),
 array([[ 2],
        [ 8],
        [14],
        [20],
        [26],
        [32]]),
 array([[ 3],
        [ 9],
        [15],
        [21],
        [27],
        [33]]),
 array([[ 4],
        [10],
        [16],
        [22],
        [28],
        [34]]),
 array([[ 5],
        [11],
        [17],
        [23],
        [29],
        [35]]),
 array([[ 6],
        [12],
        [18],
        [24],
        [30],
        [36]])]

In [41]:
np.vsplit(a,3)

[array([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]]),
 array([[13, 14, 15, 16, 17, 18],
        [19, 20, 21, 22, 23, 24]]),
 array([[25, 26, 27, 28, 29, 30],
        [31, 32, 33, 34, 35, 36]])]