In [2]:
import numpy as np

Numpy indexing and slicing of vectors

In [3]:
arr=np.arange(11, 21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [4]:
arr[9]

np.int64(20)

In [ ]:
arr[1:5]

array([12, 13, 14, 15, 16, 17, 18, 19, 20])

In [11]:
arr[1:]

array([12, 13, 14, 15, 16, 17, 18, 19, 20])

In [12]:
arr[:5]

array([11, 12, 13, 14, 15])

In [13]:
arr[3::2]

array([14, 16, 18, 20])

Numpy Indexing and Slicing of Matrix 

In [14]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [15]:
arr[0]

array([1, 2, 3, 4, 5])

In [16]:
arr[3]

array([16, 17, 18, 19, 20])

In [17]:
arr[0,0]

np.int64(1)

In [18]:
arr[0,4]

np.int64(5)

In [20]:
arr[5,4]

np.int64(30)

In [23]:
slice=arr[0:2,1:3]
slice

array([[2, 3],
       [7, 8]])

In [24]:
arr[3:6,3:5]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [25]:
arr[3:,3:]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [26]:
arr[:,2]

array([ 3,  8, 13, 18, 23, 28])

In [28]:
arr[2:4,1:4]

array([[12, 13, 14],
       [17, 18, 19]])

Boolean Indexing

In [38]:
arr=np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [39]:
bool_index=arr%2==0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [40]:
arr = arr[bool_index]
arr

array([12, 14, 16, 18, 20])